name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: macos-13
    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_15.0.1.app/Contents/Developer'
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9.0"
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-Toast-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-NSAbout
      - name: Build
        run: xcodebuild build -scheme Toast -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15 Pro"
